src/Entity/Projet.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ProjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ProjetRepository::class)]
#[ApiResource(
    collectionOperations: [
        'get' => ['normalization_context' => ['groups' => 'Projet:list']],
        'post' => ['normalization_context' => ['groups' => 'Projet:list']],
        
      
    ],
    itemOperations: [
        'get' => ['normalization_context' => ['groups' => 'Projet:item']],
        'put' => ['normalization_context' => ['groups' => 'Projet:item']],
        'delete' => ['normalization_context' => ['groups' => 'Projet:item']]
        
       
    ],
    
    paginationEnabled: false
)]
class Projet
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?string $description = null;

    #[ORM\Column]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?float $montant = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255)]
    #[Groups(['Projet:list', 'Projet:item'])]
    private ?string $statut = null;

    #[ORM\ManyToOne(inversedBy: 'Projet')]
    private ?MaisonDeCulte $IdMaisonDeCulte = null;

    #[ORM\OneToMany(mappedBy: 'IdProjet', targetEntity: Contribution::class)]
    private Collection $Contribution;

    #[ORM\OneToOne(targetEntity: self::class, inversedBy: 'Statut')]
    private ?Statut $IdStatut = null;



    #[ORM\ManyToOne(inversedBy: 'Projet')]
    private ?Donateur $IdDonateur = null;

    

    public function __construct()
    {
        $this->Contribution = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): static
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getIdMaisonDeCulte(): ?MaisonDeCulte
    {
        return $this->IdMaisonDeCulte;
    }

    public function setIdMaisonDeCulte(?MaisonDeCulte $IdMaisonDeCulte): static
    {
        $this->IdMaisonDeCulte = $IdMaisonDeCulte;

        return $this;
    }

    /**
     * @return Collection<int, Contribution>
     */
    public function getContribution(): Collection
    {
        return $this->Contribution;
    }

    public function addContribution(Contribution $contribution): static
    {
        if (!$this->Contribution->contains($contribution)) {
            $this->Contribution->add($contribution);
            $contribution->setIdProjet($this);
        }

        return $this;
    }

    public function removeContribution(Contribution $contribution): static
    {
        if ($this->Contribution->removeElement($contribution)) {
            // set the owning side to null (unless already changed)
            if ($contribution->getIdProjet() === $this) {
                $contribution->setIdProjet(null);
            }
        }

        return $this;
    }

    public function getIdStatut(): ?self
    {
        return $this->IdStatut;
    }

    public function setIdStatut(?self $IdStatut): static
    {
        $this->IdStatut = $IdStatut;

        return $this;
    }
    public function getIdDonateur(): ?Donateur
    {
        return $this->IdDonateur;
    }

    public function setIdDonateur(?Donateur $IdDonateur): static
    {
        $this->IdDonateur = $IdDonateur;

        return $this;
    }

    /**
     * @return Collection<int, Statut>
     */
  
}

src/Form/ProjetType.php
<?php

namespace App\Form;

use App\Entity\Projet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProjetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('montant')
            ->add('date_debut')
            ->add('date_fin')
            ->add('statut')
            ->add('IdMaisonDeCulte')
            ->add('IdStatut')
            ->add('IdDonateur')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Projet::class,
        ]);
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use App\Entity\Projet;
use App\Form\ProjetType;
use App\Repository\ProjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/projet')]
class ProjetController extends AbstractController
{
    #[Route('/', name: 'app_projet_index', methods: ['GET'])]
    public function index(ProjetRepository $projetRepository): Response
    {
        return $this->render('projet/index.html.twig', [
            'projets' => $projetRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_projet_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $projet = new Projet();
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($projet);
            $entityManager->flush();

            return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projet/new.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projet_show', methods: ['GET'])]
    public function show(Projet $projet): Response
    {
        return $this->render('projet/show.html.twig', [
            'projet' => $projet,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_projet_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProjetType::class, $projet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('projet/edit.html.twig', [
            'projet' => $projet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_projet_delete', methods: ['POST'])]
    public function delete(Request $request, Projet $projet, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$projet->getId(), $request->request->get('_token'))) {
            $entityManager->remove($projet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_projet_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/projet/_delete_form.html.twig
<form method="post" action="{{ path('app_projet_delete', {'id': projet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ projet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/projet/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/projet/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Projet{% endblock %}

{% block body %}
    <h1>Edit Projet</h1>

    {{ include('projet/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_projet_index') }}">back to list</a>

    {{ include('projet/_delete_form.html.twig') }}
{% endblock %}

templates/projet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet index{% endblock %}

{% block body %}
    <h1>Projet index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Description</th>
                <th>Montant</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for projet in projets %}
            <tr>
                <td>{{ projet.id }}</td>
                <td>{{ projet.titre }}</td>
                <td>{{ projet.description }}</td>
                <td>{{ projet.montant }}</td>
                <td>{{ projet.dateDebut ? projet.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ projet.dateFin ? projet.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ projet.statut }}</td>
                <td>
                    <a href="{{ path('app_projet_show', {'id': projet.id}) }}">show</a>
                    <a href="{{ path('app_projet_edit', {'id': projet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_projet_new') }}">Create new</a>
{% endblock %}

templates/projet/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Projet{% endblock %}

{% block body %}
    <h1>Create new Projet</h1>

    {{ include('projet/_form.html.twig') }}

    <a href="{{ path('app_projet_index') }}">back to list</a>
{% endblock %}

templates/projet/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Projet{% endblock %}

{% block body %}
    <h1>Projet</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ projet.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ projet.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ projet.description }}</td>
            </tr>
            <tr>
                <th>Montant</th>
                <td>{{ projet.montant }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ projet.dateDebut ? projet.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ projet.dateFin ? projet.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ projet.statut }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_projet_index') }}">back to list</a>

    <a href="{{ path('app_projet_edit', {'id': projet.id}) }}">edit</a>

    {{ include('projet/_delete_form.html.twig') }}
{% endblock %}